name: Test the action

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          
        - name: macOS
          os: macos-latest

        - name: Android 
          os: ubuntu-latest
          platform: "android" 

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: geode-sdk/textureldr
          path: textureldr

      - name: Build the mod
        uses: fleeym/build-geode-mod@main
        with:
          sdk: nightly
          build-config: RelWithDebInfo
          path: textureldr
          combine: true
          platform-override: ${{ matrix.config.platform }}
      
  package:
    name: Package both builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: geode-sdk/build-geode-mod/@combine
        id: build

      - uses: actions/upload-artifact@v3
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
